displayName: External traefik config provider
type: provider
iconPath: .assets/icon.png

import: github.com/iappx/external_traefik_config_plugin

summary: 'The plugin allows you to get routers of third-party instances traefik by api and send requests to them through the creation of a separate service in the base instance'

testData:
  pollInterval: 2s
  instanceMap:
    another-instance:
      apiHost: http://dashboard.traefik-instance.com
      entryPoints:
        - https
      credentials:
        username: user
        password: password
      service:
        loadBalancer:
          servers:
            - url: http://192.168.0.1:10080
          passHostHeader: true